-- Week 4 seed: Templates & Clauses
-- Run once in Supabase SQL editor after core schema is in place.

-- Global templates (org_id is null)

insert into public.template (org_id, name, category, description, default_prompt, is_active)
values
  (null, 'Mutual NDA', 'core_operational',
   'Two-way non-disclosure agreement for sharing confidential information between parties.',
   'Draft a mutual NDA between the parties using neutral, startup-friendly terms and plain English.',
   true),
  (null, 'One-way NDA', 'core_operational',
   'One-way NDA where only one party discloses confidential information.',
   'Draft a one-way NDA where only the disclosing party is sharing sensitive information.',
   true),
  (null, 'Master Services Agreement (MSA)', 'core_operational',
   'Master Services Agreement setting overall commercial and legal terms for services.',
   'Draft a master services agreement between a service provider and a customer, with modular SOWs.',
   true),
  (null, 'Statement of Work (SOW)', 'core_operational',
   'SOW to attach to an MSA covering scope, deliverables, milestones and pricing.',
   'Draft a statement of work describing scope, deliverables, milestones and fees under an existing MSA.',
   true),
  (null, 'SaaS Subscription Agreement', 'commercial_deal',
   'Standard SaaS subscription terms for B2B software.',
   'Draft a SaaS subscription agreement for a B2B software product with monthly or annual fees.',
   true),
  (null, 'Consulting Agreement', 'commercial_deal',
   'Consulting services agreement for independent contractors or firms.',
   'Draft a consulting agreement for an independent contractor providing strategic or technical services.',
   true),
  (null, 'Employment Agreement (Full-time)', 'core_operational',
   'Full-time employment contract for a salaried employee.',
   'Draft a full-time employment agreement for a new team member, including IP assignment and confidentiality.',
   true),
  (null, 'Contractor Agreement', 'core_operational',
   'Agreement for independent contractors and freelancers.',
   'Draft an independent contractor agreement with clear scope, deliverables and IP ownership.',
   true),
  (null, 'Share Purchase Agreement', 'corporate_finance',
   'Share purchase agreement for investors buying equity.',
   'Draft a share purchase agreement for an early-stage equity financing round.',
   true),
  (null, 'Shareholders Agreement', 'corporate_finance',
   'Shareholders agreement between founders and investors.',
   'Draft a shareholders agreement covering governance, vesting, transfer restrictions and exit.',
   true),
  (null, 'SAFE (Simple Agreement for Future Equity)', 'corporate_finance',
   'SAFE-style early-stage financing instrument.',
   'Draft a SAFE-style agreement for a seed investor, using common startup-friendly terms.',
   true),
  (null, 'Loan Agreement', 'corporate_finance',
   'Simple loan agreement for a fixed-term loan with interest.',
   'Draft a simple loan agreement with clear principal, interest rate, term and repayment schedule.',
   true),
  (null, 'Memorandum of Understanding (MOU)', 'commercial_deal',
   'Non-binding MOU summarizing key deal points.',
   'Draft a short MOU summarizing the key commercial terms the parties intend to negotiate into a full contract.',
   true),
  (null, 'Letter of Intent (LOI)', 'commercial_deal',
   'LOI for potential transaction (investment, sale, partnership).',
   'Draft a non-binding LOI outlining key terms for a potential transaction, with limited binding clauses.',
   true),
  (null, 'Data Processing Addendum (DPA)', 'core_operational',
   'DPA to attach to service agreements for data privacy compliance.',
   'Draft a data processing addendum covering data protection, sub-processors and security commitments.',
   true);

-- Clauses library (global)

insert into public.clause (org_id, name, category, jurisdiction, body)
values
  (null, 'Confidentiality (Standard)', 'core_business', null,
   'Each party agrees to keep confidential all non-public information disclosed by the other party and to use it solely for the purpose of performing its obligations under the agreement.'),
  (null, 'Intellectual Property Ownership', 'core_business', null,
   'Except as expressly stated in the agreement, each party retains all right, title and interest in and to its pre-existing intellectual property. All new deliverables expressly paid for by the customer will be owned by the customer, subject to the provider''s retained rights in its underlying tools and know-how.'),
  (null, 'Non-solicitation', 'core_business', null,
   'During the term of the agreement and for twelve (12) months thereafter, neither party will knowingly solicit for employment any employee of the other party who was materially involved in the relationship, except in connection with general solicitations.'),
  (null, 'Term and Termination (30 days)', 'commercial_operational', null,
   'The agreement will commence on the effective date and continue until terminated. Either party may terminate for convenience upon thirty (30) days'' prior written notice, or immediately for material breach that is not cured within thirty (30) days.'),
  (null, 'Governing Law (Delaware)', 'risk_liability', 'US',
   'This agreement will be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of laws principles.'),
  (null, 'Limitation of Liability (Cap)', 'risk_liability', null,
   'Except for liability arising from gross negligence, wilful misconduct or infringement of third-party intellectual property rights, each party''s aggregate liability under the agreement will not exceed the fees actually paid by the customer under the agreement in the twelve (12) months preceding the claim.'),
  (null, 'Indemnification (IP Infringement)', 'risk_liability', null,
   'The provider will indemnify and defend the customer against third-party claims alleging that the services infringe any intellectual property right, subject to customary conditions and exclusions.'),
  (null, 'Payment Terms (Net 30)', 'commercial_operational', null,
   'Unless otherwise stated in the order form, all undisputed invoices are due and payable within thirty (30) days of the invoice date. Overdue amounts may accrue interest at the lesser of 1.5% per month or the maximum rate permitted by law.'),
  (null, 'Payment Milestones', 'commercial_operational', null,
   'Fees will be invoiced based on the milestones defined in the statement of work. Each milestone is deemed accepted unless the customer raises a substantiated written objection within ten (10) days of delivery.'),
  (null, 'Data Protection (General)', 'core_business', 'EU',
   'The parties will process personal data in accordance with applicable data protection laws. Where required, the parties will enter into a separate data processing agreement that forms part of the main agreement.'),
  (null, 'Dispute Resolution (Arbitration)', 'risk_liability', null,
   'Any dispute arising out of or in connection with the agreement will be finally resolved by binding arbitration under the rules specified in the agreement, with judgment on the award enforceable by any court of competent jurisdiction.');

